const languages = [
  { title: "English", subtitle: "English" },
  { title: "Afrikaans", subtitle: "Afrikaans" },
  { title: "Amharic", subtitle: "አማርኛ" },
  { title: "Arabic", subtitle: "العربية" },
  { title: "Arabic (Egypt)", subtitle: "عربي مصري" },
  { title: "Arabic (Morocco)", subtitle: "العربية المغربية" },
  { title: "Arabic (Saudi Arabia)", subtitle: "العربية السعودية" },
  { title: "Azerbaijani", subtitle: "Azərbaycanca" },
  { title: "Bulgarian", subtitle: "Български" },
  { title: "Bhojpuri", subtitle: "भोजपुरी" },
  { title: "Bengali", subtitle: "বাংলা" },
  { title: "Bosnian", subtitle: "Bosanski" },
  { title: "Catalan", subtitle: "Català" },
  { title: "Czech", subtitle: "Čeština" },
  { title: "Danish", subtitle: "Dansk" },
  { title: "German", subtitle: "Deutsch" },
  { title: "Greek", subtitle: "Ελληνικά" },
  { title: "English (United Kingdom)", subtitle: "English" },
  { title: "European Spanish", subtitle: "Español de España" },
  { title: "Latin American Spanish", subtitle: "Español de Latinoamérica" },
  { title: "Spanish (Argentina)", subtitle: "Español (Argentina)" },
  { title: "Spanish (Mexico)", subtitle: "Español (México)" },
  { title: "Estonian", subtitle: "Eesti" },
  { title: "Basque", subtitle: "Euskara" },
  { title: "Persian", subtitle: "فارسی" },
  { title: "Finnish", subtitle: "Suomeksi" },
  { title: "Filipino", subtitle: "Filipino" },
  { title: "French", subtitle: "Français" },
  { title: "Canadian French", subtitle: "Français Canadien" },
  { title: "Galician", subtitle: "Galego" },
  { title: "Gujarati", subtitle: "ગુજરાતી" },
  { title: "Hebrew", subtitle: "עברית" },
  { title: "Hindi", subtitle: "हिन्दी" },
  { title: "Croatian", subtitle: "Hrvatski" },
  { title: "Hungarian", subtitle: "Magyar" },
  { title: "Indonesian", subtitle: "Bahasa Indonesia" },
  { title: "Icelandic", subtitle: "Íslenska" },
  { title: "Italian", subtitle: "Italiano" },
  { title: "Japanese", subtitle: "日本語" },
  { title: "Kannada", subtitle: "ಕನ್ನಡ" },
  { title: "Korean", subtitle: "한국어" },
  { title: "Lithuanian", subtitle: "Lietuvių" },
  { title: "Latvian", subtitle: "Latviešu" },
  { title: "Malayalam", subtitle: "മലയാളം" },
  { title: "Marathi", subtitle: "मराठी" },
  { title: "Malay", subtitle: "Melayu" },
  { title: "Macedonian", subtitle: "Македонски" },
  { title: "Norwegian", subtitle: "Norsk" }
];

export default languages;
